language: node_js
node_js:
  - "10"
addons:
  chrome: stable
jobs:
  include:
    - stage: "axe accessibility test"
      script: cd axe-example && npm install && npm run test
    - stage: "pa11y accessibility test reports"
      script: echo report
