language: node_js
node_js:
  - "10"
addons:
  chrome: stable
jobs:
  include:
    - stage: "axe continuum pa11y accessibility test"
      script: cd axe-example && npm install && npm run test
      script: cd continuum-example && npm install && npm run test
      script: cd pa11y-example && npm install && npm run test
