language: node_js
addons:
  chrome: stable
jobs:
  include:
    - stage: "axe accessibility test"
      script: sh ./axe-example/travis_ci.sh
      script: 
    - stage: "pa11y accessibility test reports"
      script: echo report
